server:
  servlet:
    context-path: /tn-social-carpooling
app:
  base:
    url: http://localhost:4200

spring:
  social:
    facebook:
      appId: 467330227398390
      appSecret: 1d5ae43ec6e3344f5328fd4f67fadcf3
  data:
    mongodb:
      host: localhost
      port: 27017
      database: social_carpooling
